<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<link rel="stylesheet" href="../../resources/css/note.css"/>
</head>
<body>
<h1>PHP Exception Handling</h1>
<p>Exceptions are used to change the normal flow of a script if a specified error occurs.</p>
<hr/>

<h2>What is an Exception</h2>
<p>With PHP 5 came a new object oriented way of dealing with errors.</p>
<p>Exception handling is used to change the normal flow of the code execution if a specified error (exceptional) condition occurs. This condition is called an exception.</p>
<p>This is what normally happens when an exception is triggered:</p>
<ul>
<li>The current code state is saved</li>
<li>The code execution will switch to a predefined (custom) exception handler function</li>
<li>Depending on the situation, the handler may then resume the execution from the saved code state, terminate the script execution or continue the script from a different location in the code</li>
</ul>
<p>We will show different error handling methods:</p>
<ul>
<li>Basic use of Exceptions</li>
<li>Creating a custom exception handler</li>
<li>Multiple exceptions</li>
<li>Re-throwing an exception</li>
<li>Setting a top level exception handler</li>
</ul>
<p><b>Note:</b> Exceptions should only be used with error conditions, and should not be used to jump to another place in the code at a specified point.</p>
<hr/>

<h2>Basic Use of Exceptions</h2>
<p>When an exception is thrown, the code following it will not be executed, and PHP will try to find the matching "catch" block.</p>
<p>If an exception is not caught, a fatal error will be issued with an "Uncaught Exception" message.</p>
<p>Lets try to throw an exception without catching it:</p>
<code><pre>
&lt;?php
//create function with an exception
function checkNum($number) {
  if($number&gt;1) {
    throw new Exception("Value must be 1 or below");
  }
  return true;
}

//trigger exception
checkNum(2);
?&gt;
</pre></code>
<p>The code above will get an error like this:</p>
<code><pre>
<b>Fatal error:</b> Uncaught exception 'Exception'
with message 'Value must be 1 or below' in C:\webfolder\test.php:6
Stack trace: #0 C:\webfolder\test.php(12):
checkNum(28) #1 {main} thrown in <b>C:\webfolder\test.php</b> on line <b>6</b>
</pre></code>
<h3>try, throw and catch</h3>
<p>To avoid the error from the example above, we need to create the proper code to handle an exception.</p>
<p>Proper exception code should include:</p>
<ol>
<li>Try - A function using an exception should be in a "try" block. If the exception does not trigger, the code will continue as normal. However if the exception triggers, an exception is "thrown"</li>
<li>Throw - This is how you trigger an exception. Each "throw" must have at least one "catch"</li>
<li>Catch - A "catch" block retrieves an exception and creates an object containing the exception information</li>
</ol>
<p>Lets try to trigger an exception with valid code:</p>
<code><pre>
&lt;?php
//create function with an exception
function checkNum($number) {
  if($number&gt;1) {
    throw new Exception("Value must be 1 or below");
  }
  return true;
}

//trigger exception in a "try" block
try {
  checkNum(2);
  //If the exception is thrown, this text will not be shown
  echo 'If you see this, the number is 1 or below';
}

//catch exception
catch(Exception $e) {
  echo 'Message: ' .$e-&gt;getMessage();
}
?&gt;
</pre></code>
<p>The code above will get an error like this:</p>
<code><pre>
Message: Value must be 1 or below
</pre></code>
<h3>Example explained:</h3>
<p>The code above throws an exception and catches it:</p>
<ul>
<li>The checkNum() function is created. It checks if a number is greater than 1. If it is, an exception is thrown</li>
<li>The checkNum() function is called in a "try" block</li>
<li>The exception within the checkNum() function is thrown</li>
<li>The "catch" block retrieves the exception and creates an object ($e) containing the exception information</li>
<li>The error message from the exception is echoed by calling $e-&gt;getMessage() from the exception object</li>
</ul>
<p>However, one way to get around the "every throw must have a catch" rule is to set a top level exception handler to handle errors that slip through.</p>
<hr/>

<h2>Creating a Custom Exception Class</h2>
<p>Creating a custom exception handler is quite simple. We simply create a special class with functions that can be called when an exception occurs in PHP. The class must be an extension of the exception class.</p>
<p>The custom exception class inherits the properties from PHP's exception class and you can add custom functions to it.</p>
<p>Lets create an exception class:</p>
<code><pre>
&lt;?php
class customException extends Exception {
  public function errorMessage() {
    //error message
    $errorMsg = 'Error on line '.$this-&gt;getLine().' in '.$this-&gt;getFile()
    .': &lt;b&gt;'.$this-&gt;getMessage().'&lt;/b&gt; is not a valid E-Mail address';
    return $errorMsg;
  }
}

$email = "someone@example...com";

try {
  //check if
  if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE) {
    //throw exception if email is not valid
    throw new customException($email);
  }
}

catch (customException $e) {
  //display custom message
  echo $e-&gt;errorMessage();
}
?&gt;
</pre></code>
<p>The new class is a copy of the old exception class with an addition of the errorMessage() function. Since it is a copy of the old class, and it inherits the properties and methods from the old class, we can use the exception class methods like getLine() and getFile() and getMessage().</p>
<h3>Example explained:</h3>
<p>The code above throws an exception and catches it with a custom exception class:</p>
<ul>
<li>The customException() class is created as an extension of the old exception class. This way it inherits all methods and properties from the old exception class</li>
<li>The errorMessage() function is created. This function returns an error message if an e-mail address is invalid</li>
<li>The $email variable is set to a string that is not a valid e-mail address</li>
<li>The "try" block is executed and an exception is thrown since the e-mail address is invalid</li>
<li>The "catch" block catches the exception and displays the error message</li>
</ul>

<h2>Multiple Exceptions</h2>
<p>It is possible for a script to use multiple exceptions to check for multiple conditions.</p>
<p>It is possible to use several if..else blocks, a switch, or nest multiple exceptions. These exceptions can use different exception classes and return different error messages:</p>
<code><pre>
&lt;?php
class customException extends Exception {
  public function errorMessage() {
    //error message
    $errorMsg = 'Error on line '.$this-&gt;getLine().' in '.$this-&gt;getFile()
    .': &lt;b&gt;'.$this-&gt;getMessage().'&lt;/b&gt; is not a valid E-Mail address';
    return $errorMsg;
  }
}

$email = "someone@example.com";

try {
  //check if
  if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE) {
    //throw exception if email is not valid
    throw new customException($email);
  }
  //check for "example" in mail address
  if(strpos($email, "example") !== FALSE) {
    throw new Exception("$email is an example e-mail");
  }
}

catch (customException $e) {
  echo $e-&gt;errorMessage();
}

catch(Exception $e) {
  echo $e-&gt;getMessage();
}
?&gt;
</pre></code>
<h3>Example explained:</h3>
<p>The code above tests two conditions and throws an exception if any of the conditions are not met:</p>
<ul>
<li>The customException() class is created as an extension of the old exception class. This way it inherits all methods and properties from the old exception class</li>
<li>The errorMessage() function is created. This function returns an error message if an e-mail address is invalid</li>
<li>The $email variable is set to a string that is a valid e-mail address, but contains the string "example"</li>
<li>The "try" block is executed and an exception is not thrown on the first condition</li>
<li>The second condition triggers an exception since the e-mail contains the string "example"</li>
<li>The "catch" block catches the exception and displays the correct error message</li>
</ul>
<p>If the exception thrown were of the class customException and there were no customException catch, only the base exception catch, the exception would be handled there.</p>
<hr/>

<h2>Re-throwing Exceptions</h2>
<p>Sometimes, when an exception is thrown, you may wish to handle it differently than the standard way. It is possible to throw an exception a second time within a "catch" block.</p>
<p>A script should hide system errors from users. System errors may be important for the coder, but are of no interest to the user. To make things easier for the user you can re-throw the exception with a user friendly message:</p>
<code><pre>
&lt;?php
class customException extends Exception {
  public function errorMessage() {
    //error message
    $errorMsg = $this-&gt;getMessage().' is not a valid E-Mail address.';
    return $errorMsg;
  }
}

$email = "someone@example.com";

try {
  try {
    //check for "example" in mail address
    if(strpos($email, "example") !== FALSE) {
      //throw exception if email is not valid
      throw new Exception($email);
    }
  }
  catch(Exception $e) {
    //re-throw exception
    throw new customException($email);
  }
}

catch (customException $e) {
  //display custom message
  echo $e-&gt;errorMessage();
}
?&gt;
</pre></code>
</body>
</html>
